Repository fusionjs/fusion-plugin-i18n, pull requests merged in 2018-09, with the labels that each got.

#157 Pass locale code as a header to translations request
  src/__tests__/index.browser.js
  src/browser.js
  src/node.js
Labels: feature

#158 Release v1.1.0
  package.json
Labels: release

#159 Fix client-side loaded chunk tracking
  src/__tests__/index.browser.js
  src/browser.js
Labels: bugfix

#160 Improve Flow type
  .flowconfig
  README.md
  chunk-translation-map.js
  flow-typed/locale.js
  package.json
  src/__tests__/index.browser.js
  src/__tests__/index.node.js
  src/browser.js
  src/index.js
  src/loader.js
  src/node.js
  src/tokens.js
  src/types.js
  yarn.lock
Labels: bugfix

#161 Restore fusion-core flow libdefs
  .flowconfig
  package.json
  src/__tests__/index.node.js
  yarn.lock
Labels: bugfix

#164 Fix treeshaking for plugin exports
  src/browser.js
  src/node.js
Labels: bugfix

#165 Export 'null' for browser bundle for loader.js
  src/loader.js
Labels: bugfix

#166 Release v1.1.1-0
  package.json
Labels: prerelease, release
