Repository fusionjs/fusion-plugin-i18n, pull requests merged in 2018-10, with the labels that each got.

#172 Upgrade dependencies and fix new flow error
  package.json
  src/types.js
  yarn.lock
Labels: dependencies, greenkeeping

#176 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#181 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
