Repository fusionjs/fusion-plugin-i18n, pull requests merged in 2018-11, with the labels that each got.

#185 Update flow usage and export type
  package.json
  src/index.js
  src/node.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#188 Release v1.1.4-0
  package.json
Labels: release

#189 Release v1.1.4
  package.json
Labels: release

#191 Release v1.1.5-0
  package.json
Labels: release

#192 Release v1.1.5
  package.json
Labels: release

#193 Add flow-typed/ folder to export for consumers
  package.json
Labels: bugfix

#194 Release v1.1.6-0
  package.json
Labels: prerelease, release

#195 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
